name: Docker
on:
  workflow_call:
    inputs:
      VERSION:
        description: 'plugin version'
        required: true
        type: string


env:
  CONTAINER_REGISTRY: us-docker.pkg.dev/spinnaker-community/docker
  REPO: ${GITHUB_REPOSITORY##*/}

jobs:   
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    
    - uses: actions/download-artifact@v2
      with:
        name: build             
    
    - name: Print
      run: |
        set -vx
        echo ${{ inputs.VERSION }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: setup docker buildx
      uses: docker/setup-buildx-action@v2

    # - name: Login
    #   uses: docker/login-action@v1
    #   with:
    #     registry: docker.artifactory.homedepot.com
    #     username: ${{ secrets.ARTIFACTORY_USER }}
    #     password: ${{ secrets.ARTIFACTORY_TOKEN }}
        
    # - name: Build and push
    #   id: docker_build
    #   uses: docker/build-push-action@v4
    #   with:
    #     context: .
    #     push: true
    #     tags: |
    #         "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{ github.ref_name }}-latest"
    #         "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{ steps.build_variables.outputs.VERSION }}"