name: Docker
on:
  workflow_call:
    inputs:
      RELEASE_VERSION:
        description: 'image version'
        required: true
        type: string

env:
  CONTAINER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  REPO_SHORT_NAME: ${GITHUB_REPOSITORY#*/}

jobs:   
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
    
    - uses: actions/download-artifact@v3
      with:
        name: build
        path: ./build             

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: setup docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Login
      uses: docker/login-action@v2
      with:
        registry: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set release version
      run: echo "RELEASE_VERSION=$(echo ${{ inputs.RELEASE_VERSION }} | sed 's/+/-/g')" >> $GITHUB_ENV

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
          ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        labels: |
          org.opencontainers.image.title=${{ env.REPO_SHORT_NAME }}
          org.opencontainers.image.source=https://github.com/${{ env.IMAGE_NAME }}
          org.opencontainers.image.version=${{ env.RELEASE_VERSION }}
