name: Docker
on:
  workflow_call:

env:
  CONTAINER_REGISTRY: us-docker.pkg.dev/spinnaker-community/docker

jobs:   
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    
    - uses: actions/download-artifact@v2
      with:
        name: build             
    
    - name: Prepare build variables
      id: build_variables
      run: |
        set -vx
        echo REPO=${GITHUB_REPOSITORY##*/} >> $GITHUB_OUTPUT
        echo VERSION="$(git describe --tags --abbrev=0 --match="v[0-9]*" | cut -c2-)-dev-${GITHUB_REF_NAME}-$(git rev-parse --short HEAD)-$(date --utc +'%Y%m%d%H%M')" >> $GIHUB_OUTPUT

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: setup docker buildx
      uses: docker/setup-buildx-action@v2

    # - name: Login
    #   uses: docker/login-action@v1
    #   with:
    #     registry: docker.artifactory.homedepot.com
    #     username: ${{ secrets.ARTIFACTORY_USER }}
    #     password: ${{ secrets.ARTIFACTORY_TOKEN }}
        
    # - name: Build and push
    #   id: docker_build
    #   uses: docker/build-push-action@v4
    #   with:
    #     context: .
    #     push: true
    #     tags: |
    #         "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{ github.ref_name }}-latest"
    #         "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{ steps.build_variables.outputs.VERSION }}"