name: Release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
    - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"
    - "v[0-9]+.[0-9]+.[0-9]+\\+[0-9]+"

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Assemble release info
        id: release_info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          . .github/workflows/release_info.sh ${{ github.event.repository.full_name }} 
          echo CHANGELOG=$(echo -e "${CHANGELOG}") >> $GITHUB_ENV
          echo SKIP_RELEASE=${SKIP_RELEASE} >> $GITHUB_ENV
          echo IS_CANDIDATE=${IS_CANDIDATE} >> $GITHUB_ENV
          echo RELEASE_VERSION=${RELEASE_VERSION} >> $GITHUB_ENV

      - name: build docker image
        if: env.SKIP_RELEASE == 'false'
        id: build-docker-image
        uses: ./.github/workflows/docker-push.yml

      - uses: actions/download-artifact@v3
        with:
          name: build
          path: ./build

      - name: Create release
        if: env.SKIP_RELEASE == 'false'
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ${{ env.CHANGELOG }}
          draft: false
          name: ${{ github.event.repository.name }} ${{ github.ref_name }}
          prerelease: ${{ env.IS_CANDIDATE }}
          tag_name: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./build/distributions/${{ github.event.repository.name }}-${{ env.RELEASE_VERSION }}.zip

      - name: Add release to plugin repo
        if: env.SKIP_RELEASE == 'false'
        uses: armory-io/plugin-metadata-updater@master
        env:
          GITHUB_OAUTH: ${{secrets.GITHUB_TOKEN}}
        with:
          metadata: ./build/distributions/plugin-info.json
          metadata_repo_url: https://github.com/one-thd/spinnaker-plugins
          binary_url: ${{ fromJSON(steps.create-release.outputs.assets)[0].browser_download_url }}