name: Release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
    - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"
    - "v[0-9]+.[0-9]+.[0-9]+\\+[0-9]+"

jobs:
  build:
    uses: ./.github/workflows/build.yml

  docker: 
    needs: build
    uses: ./.github/workflows/docker-push.yml

  release:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Assemble release info
        id: release_info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          . .github/workflows/release_info.sh ${{ github.event.repository.full_name }} 
          echo CHANGELOG=$(echo -e "${CHANGELOG}") >> $GITHUB_ENV
          echo SKIP_RELEASE=${SKIP_RELEASE} >> $GITHUB_ENV
          echo IS_CANDIDATE=${IS_CANDIDATE} >> $GITHUB_ENV
          echo RELEASE_VERSION=${RELEASE_VERSION} >> $GITHUB_ENV

      - uses: actions/download-artifact@v3
        with:
          name: build
          path: ./build

      - name: Create release
        if: env.SKIP_RELEASE == 'false'
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ${{ env.CHANGELOG }}
          draft: false
          name: ${{ github.event.repository.name }} ${{ github.ref_name }}
          prerelease: ${{ env.IS_CANDIDATE }}
          tag_name: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./build/distributions/${{ github.event.repository.name }}-${{ env.RELEASE_VERSION }}.zip

      - name: Checkout plugin repo
        if: env.SKIP_RELEASE == 'false'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: one-thd/spinnaker-plugins
          ssh-key: ${{ secrets.SPINNAKER_PLUGINS_REPO_SSH }}
          path: spinnaker-plugins

      - name: Add plugin release
        if: env.SKIP_RELEASE == 'false'
        run: |
          set -vx
          go run .github/workflows/addPluginReleaseToRepo.go "{\"org\": \"homedepot\", \"repo\": \"spin-observatory-plugin\", \"release\": $(cat build/distributions/plugin-info.json)}"

      - name: Commit and push
        if: env.SKIP_RELEASE == 'false'
        run: |
          set -vx
          cd spinnaker-plugins
          git status